from sqlalchemy import String, Enum, Integer, ForeignKey, DateTime, Text, Index, func, Numeric
from sqlalchemy.orm import Mapped, mapped_column, relationship
from datetime import datetime
import enum
from app.database import Base


class SiteStatus(str, enum.Enum):
    planned = 'planned'           # Запланирован
    survey = 'survey'             # Обследование
    design = 'design'             # Проектирование
    permitting = 'permitting'     # Получение разрешений
    construction = 'construction' # Строительство
    testing = 'testing'           # Тестирование
    accepted = 'accepted'         # Принят
    cancelled = 'cancelled'       # Отменён


class Site(Base):
    __tablename__ = 'sites'

    # ── Системные поля ────────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(primary_key=True, index=True)
    site_id: Mapped[str] = mapped_column(String(64), unique=True, index=True, nullable=False)
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    project_id: Mapped[int] = mapped_column(
        Integer, ForeignKey('projects.id', ondelete='SET NULL'), nullable=True, index=True
    )

    # Регион: текст для поиска/Excel + FK на справочник
    region: Mapped[str] = mapped_column(String(128), nullable=True, index=True)
    region_id: Mapped[int] = mapped_column(
        Integer, ForeignKey('regions.id', ondelete='SET NULL'), nullable=True, index=True
    )

    address: Mapped[str] = mapped_column(String(512), nullable=True)
    latitude: Mapped[float] = mapped_column(nullable=True)
    longitude: Mapped[float] = mapped_column(nullable=True)

    status: Mapped[SiteStatus] = mapped_column(
        Enum(SiteStatus, name='site_status'),
        default=SiteStatus.planned,
        nullable=False,
        index=True,
    )

    # Подрядчик
    contractor_id: Mapped[int] = mapped_column(
        Integer, ForeignKey('contractors.id', ondelete='SET NULL'), nullable=True, index=True
    )

    planned_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    planned_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    actual_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)
    actual_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    notes: Mapped[str] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    # ── Новый шаблон UCN 2.0 (2026) ────────────────────────────────────────
    row_number: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fias_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    macroregion: Mapped[str | None] = mapped_column(Text, nullable=True)
    regional_branch: Mapped[str | None] = mapped_column(Text, nullable=True)
    district: Mapped[str | None] = mapped_column(Text, nullable=True)
    rural_settlement: Mapped[str | None] = mapped_column(Text, nullable=True)

    ams_permit_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ams_permit_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    power_tu_received_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ves_tu_execution_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ves_tu_execution_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vols_ready_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vols_ready_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    po: Mapped[str | None] = mapped_column(Text, nullable=True)
    igi_visit_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    igi_visit_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    igi_preparation_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    igi_preparation_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    igi_approval_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    igi_approval_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    ams_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir_order: Mapped[str | None] = mapped_column(Text, nullable=True)
    foundation_pour_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    foundation_pour_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ams_receipt_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ams_receipt_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ams_installation_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ams_installation_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    ppo: Mapped[str | None] = mapped_column(Text, nullable=True)
    appi_kzh_preparation_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    appi_kzh_preparation_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    appi_kzh_approval_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    appi_kzh_approval_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    appi_ka_approval_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    appi_ka_approval_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    rd_release: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    tu_es_signing: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    es_tu_paper_submission: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rd_acceptance: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kzd_pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_order_signing: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    bs_equipment_issuance: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    requirement: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_trip: Mapped[str | None] = mapped_column(Text, nullable=True)
    equipment_receipt_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    equipment_receipt_fact: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    brigade_contacts: Mapped[str | None] = mapped_column(Text, nullable=True)
    pnr_plan_stage: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pnr_fact_stage: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    tu_completion_certificate: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    passport_transfer_oge: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_docs: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_order_status: Mapped[str | None] = mapped_column(Text, nullable=True)

    # ── Данные из Excel (357 полей) ────────────────────────────────────────
    bs: Mapped[float | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    tip_rabot: Mapped[str | None] = mapped_column(Text, nullable=True)
    stsepka: Mapped[str | None] = mapped_column(Text, nullable=True)
    diapazon_dlya_stsepki: Mapped[str | None] = mapped_column(Text, nullable=True)
    diapazony: Mapped[str | None] = mapped_column(Text, nullable=True)
    koordinaty: Mapped[str | None] = mapped_column(Text, nullable=True)
    povtor_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    status_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    r1: Mapped[str | None] = mapped_column(Text, nullable=True)
    r2: Mapped[str | None] = mapped_column(Text, nullable=True)
    tip_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    vladelets_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_io: Mapped[str | None] = mapped_column(Text, nullable=True)
    vysota_podvesa: Mapped[str | None] = mapped_column(Text, nullable=True)
    otvetsvennyy_oa: Mapped[str | None] = mapped_column(Text, nullable=True)
    otvetsvennyy_oirp: Mapped[str | None] = mapped_column(Text, nullable=True)
    primechanie: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_vydana_v_rabotu: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bs_vydana_v_rabotu_kommentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_otozvana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    plan_smr_odn: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    plan_smr_odn_nedelya: Mapped[str | None] = mapped_column(Text, nullable=True)
    fakt_smr_odn: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_odn: Mapped[str | None] = mapped_column(Text, nullable=True)
    prognoz_dopuska_na_smr: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_polucheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    karta_ts_poluchena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    dostup_dlya_obsledovaniya: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentari_dostup: Mapped[str | None] = mapped_column(Text, nullable=True)
    kontakt_po_dostupu_na_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    obsledovanie_bs_ispolnitel: Mapped[str | None] = mapped_column(Text, nullable=True)
    obsledovanie_bs_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    obsledovanie_bs_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_peredan_v_mts_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_obsledovanie: Mapped[str | None] = mapped_column(Text, nullable=True)
    kandidat_ts_predostavlen: Mapped[str | None] = mapped_column(Text, nullable=True)
    tip_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_ts: Mapped[float | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    adres_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    tip_ao_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    vladelets_ao_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    status_dostupa_na_otvetku: Mapped[str | None] = mapped_column(Text, nullable=True)
    kontakt_po_dostupu_na_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    obsledovanie_bs_ts_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    neobkhodimost_polucheniya_tu: Mapped[str | None] = mapped_column(Text, nullable=True)
    tu_ad_ts_zaprosheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    tu_ad_ts_polucheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_bs_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    tu_io_zaprosheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    tu_io_polucheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    tu_podpisany_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_tu: Mapped[str | None] = mapped_column(Text, nullable=True)
    aop_vypuschen_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_otdan_v_rabotu_komu: Mapped[str | None] = mapped_column(Text, nullable=True)
    aop_vypuschen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_status_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    aop_status_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_soglasovan_mts_v_ev_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_soglasovan_mts_v_ev_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_soglasovan_io_ad_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_otpravlen_io_ad_na_soglasovanie_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zamechaniya_po_aop_ot_io_ad_polucheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_soglasovan_io_ad_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_podpisan_io_ad_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    aop_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    tz_vypuscheno_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status_tz: Mapped[str | None] = mapped_column(Text, nullable=True)
    km: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir_otdan_v_rabotu_komu: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir_otdan_v_rabotu: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_vypuschen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_na_proverke_v_mts_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_na_proverke_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_proveren_mts_zamechaniya: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_prinyat_mts_bez_usl_20_22_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_prinyat_mts_bez_usl_20_22: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pir_status_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir_status_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    plan_sdachi_pir: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    nomer_tp: Mapped[str | None] = mapped_column(Text, nullable=True)
    organizatsiya_soglasuyuschaya_albom_em: Mapped[str | None] = mapped_column(Text, nullable=True)
    albom_em_sdan_v_mgen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    albom_em_podpisan_mgen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    albom_em_podpisan_mgen_i_io: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    albom_em_sdan_v_oge_usl_20_22: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    albom_em_prinyat_oge_usl_20_22_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    albom_em_prinyat_oge_usl_20_22: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    prioritety_sdachi_usl_pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentarii_em: Mapped[str | None] = mapped_column(Text, nullable=True)
    sa_pir_prostavlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_arbp_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_arbp_podgotovlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    arbp_otpravlen_na_podpisanie_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    arbp_podpisan_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_arbp_otchet_peredany_io: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otchet_psi_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otchet_psi_podgotovlen_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otchet_psi_podgotovlen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_i_arbp_otchet_psi_peredan_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    prioritety_sdachi_usl_smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentarii_4_etap: Mapped[str | None] = mapped_column(Text, nullable=True)
    neobkhodimost_rns_epb: Mapped[str | None] = mapped_column(Text, nullable=True)
    pozitsiya_s_zakazchikom: Mapped[str | None] = mapped_column(Text, nullable=True)
    ispolnitel_ekspertizy: Mapped[str | None] = mapped_column(Text, nullable=True)
    ekspertiza_vydana_v_rabotu_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    plan_predostavleniya_ekspertizy_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ekspertiza_gotova_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    f1a_zaproshena_v_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    f1a_vydana_v_rabotu_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    km_na_ams: Mapped[str | None] = mapped_column(Text, nullable=True)
    ekspertiza_komentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    tip_ves: Mapped[str | None] = mapped_column(Text, nullable=True)
    oformlenie_dogovora_tekhnologicheskogo_prisoedineniya_k_es: Mapped[str | None] = mapped_column(Text, nullable=True)
    zapros_tu_elektrosnayuzheniya_otpravlen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    tu_na_elektrosnabzhenie_poluchen_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    dogovor_elektrosnabzheniya_bs_podgotovlen: Mapped[str | None] = mapped_column(Text, nullable=True)
    pd_el_snab_soglasovan_s_ad: Mapped[str | None] = mapped_column(Text, nullable=True)
    pd_el_snab_soglasovan_s_setevoy_organizatsiey: Mapped[str | None] = mapped_column(Text, nullable=True)
    po_r1: Mapped[str | None] = mapped_column(Text, nullable=True)
    po_r2: Mapped[str | None] = mapped_column(Text, nullable=True)
    adres_dogovora_arendy_rnr: Mapped[str | None] = mapped_column(Text, nullable=True)
    dogovor_arendy_poluchen_ot_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_izmenenie_adresa_otpravlen_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_izmenenie_adresa_podpisan_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    ds_na_izmenenie_tz_otpravlen_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_izmenenie_tz_podpisan_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentarii_ds_izm_tz: Mapped[str | None] = mapped_column(Text, nullable=True)
    nalichie_so: Mapped[str | None] = mapped_column(Text, nullable=True)
    zapros_prto: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otvet_prto: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_vypuschen_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_vydan_v_rabotu_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_vypuschen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_otdan_na_podpisanie_v_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_podpisan_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    r1_status_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    r1_status_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_otpravlen_v_fbuz_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    psez_otpravlen_v_fbuz_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ez1_polucheno_ot_fbuz_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ez_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    ez1_podano_na_r1_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ez1_podano_na_r1_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r1_poluchen_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r1_poluchen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ap_r1_podpisan_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    gr_r1_prostavlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r1_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    r2_status_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    r2_status_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r1_otpravlen_vo_fbuz_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    protokol_izmereniy_poluchen_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pi_podan_na_ez2_v_fbuz: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ez_i_emp_polucheny_ot_fbuz: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ez_i_emp_podano_v_rpn: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r2_poluchen_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r2_poluchen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ap_r2_podpisan_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    gr_r2_prostavlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    r2_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_odn_fakt_aop_soglsovano_io_cs: Mapped[str | None] = mapped_column(Text, nullable=True)
    oborudovanie_cs_zakazano: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    oborudovanie_zakazano_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    oborudovanie_polucheno_v_polnom_obeme_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_gotova_k_smr_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_gotova_k_smr_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    oborudovanie_zakazano_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    oborudovanie_bs_mts_vypisano: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    planovaya_data_polucheniya_oborudovaniya_bs: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    oborudovanie_polucheno_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    dozakazy: Mapped[str | None] = mapped_column(Text, nullable=True)
    nomer_zayavki_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    oborudovanie_komentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_ts_zakaz_obor_ya: Mapped[float | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    zayavka_na_oborudovanie_ts_otpravlena_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    oborudovanie_ts_mts_vypisano: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    planovaya_data_polucheniya_oborudovaniya_ts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    oborudovanie_ts_polucheno: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    nomer_zayavki_ts: Mapped[str | None] = mapped_column(Text, nullable=True)
    oborudovanie_polucheno_v_polnom_obeme: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentariy_oborudovanie: Mapped[str | None] = mapped_column(Text, nullable=True)
    dostup_na_bs_smr_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentarii_dostup_na_bs_smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    neobkhodimost_soprovozhdeniya: Mapped[str | None] = mapped_column(Text, nullable=True)
    klyuchi: Mapped[str | None] = mapped_column(Text, nullable=True)
    zapros_int_nykh_dannykh_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    int_nye_dannye_polucheny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fio_otvetstvennogo_za_sim: Mapped[str | None] = mapped_column(Text, nullable=True)
    sim_karta_um_40: Mapped[str | None] = mapped_column(Text, nullable=True)
    um_40_v_rabote_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    pasport_na_el_schetchik_poluchen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pasport_na_el_schetchik_peredan_v_oge: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smr_klassifikator: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    polnyy_komplekt_oborudovaniya: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    prognoz_dopuska_na_bs: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    data_pnr_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    nedelya_pnr_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    nedelya_smr_prognoz: Mapped[str | None] = mapped_column(Text, nullable=True)
    nedelya_pnr_prognoz: Mapped[str | None] = mapped_column(Text, nullable=True)
    region_brigady: Mapped[str | None] = mapped_column(Text, nullable=True)
    fio_brigadir: Mapped[str | None] = mapped_column(Text, nullable=True)
    telefon: Mapped[str | None] = mapped_column(Text, nullable=True)
    nachalo_smr_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    nachalo_smr_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zavershenie_smr_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zavershenie_smr_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pnr_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pnr_fakt: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    nedelya_pnr_fakt: Mapped[float | None] = mapped_column(Numeric(precision=18, scale=4), nullable=True)
    pnr_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    avarii_po_bs: Mapped[str | None] = mapped_column(Text, nullable=True)
    km_kommentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    avtovyshka_kol_vo: Mapped[str | None] = mapped_column(Text, nullable=True)
    raschet_premialnoy: Mapped[str | None] = mapped_column(Text, nullable=True)
    fo_predostavlen_nsn_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_status_nsn: Mapped[str | None] = mapped_column(Text, nullable=True)
    fo_status_nsn_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_prinyat_nsn_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentariy_nsn: Mapped[str | None] = mapped_column(Text, nullable=True)
    fo_otpravlen_io_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_otpravlen_io_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_io_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    fo_io_status_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_prinyat_io_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fo_prinyat_io_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentrii_fo_io: Mapped[str | None] = mapped_column(Text, nullable=True)
    id_podgotovlena_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_peredana_v_mts_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_peredana_v_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_proverena_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    id_proverena_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_prinyata_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    id_prinyata_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    id_priemka_kommentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    bs_vystavlena_na_priemku_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bs_vystavlena_na_priemku_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    priemka_bs_plan_nsn_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    priemka_bs_plan_nsn_vermya: Mapped[str | None] = mapped_column(Text, nullable=True)
    priemka_bs_plan_mts_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    priemka_bs_plan_mts_vremya: Mapped[str | None] = mapped_column(Text, nullable=True)
    priemka_provedena_fakt_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    priemka_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    vn_poluchena_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vn_poluchena_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vd_poluchena_data: Mapped[str | None] = mapped_column(Text, nullable=True)
    polucheny_zamechaniya: Mapped[str | None] = mapped_column(Text, nullable=True)
    zamechaniya_pir_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    zamechaniya_pir_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zamechaniya_pir_ustraneny_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vo_otvezena_v_mts_v_bumage_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vo_prinyata_v_mts_v_bumage_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zamechaniya_pir_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    zamechaniya_smr_kommentarii: Mapped[str | None] = mapped_column(Text, nullable=True)
    trebuemye_raskh_materialy_dlya_ustraneniya: Mapped[str | None] = mapped_column(Text, nullable=True)
    trebuemoe_oborudovanie_dlya_ustraneniya_mts: Mapped[str | None] = mapped_column(Text, nullable=True)
    ustranenie_zamechaniy_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    vn_peredana_brigade: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    fio_brigadira: Mapped[str | None] = mapped_column(Text, nullable=True)
    zmechaniya_smr_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    zamechaniya_smr_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ustranenie_vn_otpravleno_v_mts_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ustranenie_vn_otpravleno_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ustranenie_vn_provereno_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zamechaniya_po_otdelam_mts_status: Mapped[str | None] = mapped_column(Text, nullable=True)
    zamechaniya_po_otdelam_mts_kommentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_prinyat_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bs_prinyata_mts_polnostyu_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bs_prinyata_mts_polnostyu: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    atp_podgotovlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    atp_podpisan_nsn: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    atp_peredan_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    atp_podpisan_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podgotovlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan_plan: Mapped[str | None] = mapped_column(Text, nullable=True)
    akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ks_11_podgotovlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ks_11_podpisan_nsn: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ks_11_peredana_v_mts: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ks_11_podpisana_polnostyu_plan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ks_11_podpisana_polnostyu_data: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    dokumenty_na_oplatu_podany: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    gr_smr_prostavlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    gr_smr_komentariy: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentariy_k_zakazu_pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_zakaz_na_pir: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_pir_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_pir_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_pir_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_pir_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_pir_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    srok_okonchaniya_rabot_po_pir: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_pir_v_storonu_po_vypuschen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    obosnovanie_prodleniya_zakaza_pir: Mapped[str | None] = mapped_column(Text, nullable=True)
    pir_faktura_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    novyy_srok_okonchaniya_zakaza_pir_dlya_prodleniya: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otsrochka_pir_soglasovana: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentariy_k_zakazu_smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_zakaz_na_smr: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_smr_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_smr_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_smr_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_smr_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_smr_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    srok_okonchaniya_rabot_po_smr: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_smr_v_storonu_po_vypuschen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    obosnovanie_prodleniya_zakaza_smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    smr_faktura_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    novyy_srok_okonchaniya_zakaza_smr_dlya_prodleniya: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otsrochka_smr_soglasovana: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentariy_k_ds_smr: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_ds_k_smr: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_smr_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_ds_na_smr_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_ds_na_smr_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_smr_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ds_na_smr_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kommentariy_k_zakazu_r1: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_zakaz_na_r1: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r1_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_r1_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_r1_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r1_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r1_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    srok_okonchaniya_rabot_po_r1: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r1_v_storonu_po_vypuschen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    obosnovanie_prodleniya_zakaza_r1: Mapped[str | None] = mapped_column(Text, nullable=True)
    r1_faktura_tekst: Mapped[str | None] = mapped_column(Text, nullable=True)
    novyy_srok_okonchaniya_zakaza_r1_dlya_prodleniya: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    otsrochka_r1_soglasovana: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentariy_k_zakazu_r2: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_zakaz_na_r2: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r2_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_r2_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_r2_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r2_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r2_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    srok_okonchaniya_rabot_po_r2: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_r2_v_storonu_po_vypuschen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    obosnovanie_prodleniya_zakaza_r2: Mapped[str | None] = mapped_column(Text, nullable=True)
    novyy_srok_okonchaniya_zakaza_r2_dlya_prodleniya: Mapped[str | None] = mapped_column(Text, nullable=True)
    servisnyy_nomer: Mapped[str | None] = mapped_column(Text, nullable=True)
    kommentarii_k_zakazu_na_avtovyshku: Mapped[str | None] = mapped_column(Text, nullable=True)
    vypustit_zakaz_na_avtovyshku: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_avtovyshku_v_rabote: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_avtovyshku_otpravlena: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    smeta_na_avtovyshku_soglasovana: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_avtovyshku_otpravlen: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    zakaz_na_avtovyshku_podpisan: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # ── Связи ────────────────────────────────────────────────────────────
    project = relationship('Project', back_populates='sites', foreign_keys=[project_id])
    contractor = relationship('Contractor', back_populates='sites', foreign_keys=[contractor_id])
    region_rel = relationship('Region', back_populates='sites', foreign_keys=[region_id])
    logs = relationship('ActionLog', back_populates='site')

    __table_args__ = (
        Index('ix_sites_region_status', 'region', 'status'),
    )
