"""Add 357 site fields from NI panel Excel + site_history already added in 003

Revision ID: 004_add_site_ni_fields
Revises: 003_add_site_history
Create Date: 2026-04-06
"""
from alembic import op
import sqlalchemy as sa

revision = '004_add_site_ni_fields'
down_revision = '003_add_site_history'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('sites', sa.Column('bs', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('sites', sa.Column('tip_rabot', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('stsepka', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('diapazon_dlya_stsepki', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('diapazony', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('koordinaty', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('povtor_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('status_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r1', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r2', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tip_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vladelets_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_io', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vysota_podvesa', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('otvetsvennyy_oa', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('otvetsvennyy_oirp', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('primechanie', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_vydana_v_rabotu', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('bs_vydana_v_rabotu_kommentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_otozvana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('plan_smr_odn', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('plan_smr_odn_nedelya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fakt_smr_odn', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_odn', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('prognoz_dopuska_na_smr', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_polucheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('karta_ts_poluchena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('dostup_dlya_obsledovaniya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentari_dostup', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kontakt_po_dostupu_na_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('obsledovanie_bs_ispolnitel', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('obsledovanie_bs_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('obsledovanie_bs_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_peredan_v_mts_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_obsledovanie', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kandidat_ts_predostavlen', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tip_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_ts', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('sites', sa.Column('adres_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tip_ao_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vladelets_ao_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('status_dostupa_na_otvetku', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kontakt_po_dostupu_na_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('obsledovanie_bs_ts_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('neobkhodimost_polucheniya_tu', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tu_ad_ts_zaprosheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('tu_ad_ts_polucheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_bs_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tu_io_zaprosheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('tu_io_polucheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('tu_podpisany_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_tu', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('aop_vypuschen_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_otdan_v_rabotu_komu', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('aop_vypuschen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_status_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('aop_status_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_soglasovan_mts_v_ev_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_soglasovan_mts_v_ev_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_soglasovan_io_ad_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_otpravlen_io_ad_na_soglasovanie_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_po_aop_ot_io_ad_polucheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_soglasovan_io_ad_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_podpisan_io_ad_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('aop_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tz_vypuscheno_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('status_tz', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('km', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pir_otdan_v_rabotu_komu', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pir_otdan_v_rabotu', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_vypuschen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_na_proverke_v_mts_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_na_proverke_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_proveren_mts_zamechaniya', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_prinyat_mts_bez_usl_20_22_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_prinyat_mts_bez_usl_20_22', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pir_status_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pir_status_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('plan_sdachi_pir', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_pir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nomer_tp', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('organizatsiya_soglasuyuschaya_albom_em', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('albom_em_sdan_v_mgen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('albom_em_podpisan_mgen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('albom_em_podpisan_mgen_i_io', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('albom_em_sdan_v_oge_usl_20_22', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('albom_em_prinyat_oge_usl_20_22_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('albom_em_prinyat_oge_usl_20_22', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('prioritety_sdachi_usl_pir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_em', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('sa_pir_prostavlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_arbp_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_arbp_podgotovlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('arbp_otpravlen_na_podpisanie_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('arbp_podpisan_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_arbp_otchet_peredany_io', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otchet_psi_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otchet_psi_podgotovlen_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otchet_psi_podgotovlen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_i_arbp_otchet_psi_peredan_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('prioritety_sdachi_usl_smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_4_etap', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('neobkhodimost_rns_epb', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pozitsiya_s_zakazchikom', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ispolnitel_ekspertizy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ekspertiza_vydana_v_rabotu_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('plan_predostavleniya_ekspertizy_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ekspertiza_gotova_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('f1a_zaproshena_v_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('f1a_vydana_v_rabotu_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('km_na_ams', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ekspertiza_komentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('tip_ves', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oformlenie_dogovora_tekhnologicheskogo_prisoedineniya_k_es', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zapros_tu_elektrosnayuzheniya_otpravlen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('tu_na_elektrosnabzhenie_poluchen_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('dogovor_elektrosnabzheniya_bs_podgotovlen', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pd_el_snab_soglasovan_s_ad', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pd_el_snab_soglasovan_s_setevoy_organizatsiey', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('po_r1', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('po_r2', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('adres_dogovora_arendy_rnr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('dogovor_arendy_poluchen_ot_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_izmenenie_adresa_otpravlen_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_izmenenie_adresa_podpisan_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ds_na_izmenenie_tz_otpravlen_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_izmenenie_tz_podpisan_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_ds_izm_tz', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nalichie_so', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zapros_prto', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otvet_prto', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_vypuschen_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_vydan_v_rabotu_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_vypuschen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_otdan_na_podpisanie_v_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_podpisan_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r1_status_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r1_status_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_otpravlen_v_fbuz_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('psez_otpravlen_v_fbuz_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ez1_polucheno_ot_fbuz_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ez_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ez1_podano_na_r1_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ez1_podano_na_r1_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r1_poluchen_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r1_poluchen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ap_r1_podpisan_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('gr_r1_prostavlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r1_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r2_status_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r2_status_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r1_otpravlen_vo_fbuz_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('protokol_izmereniy_poluchen_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pi_podan_na_ez2_v_fbuz', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ez_i_emp_polucheny_ot_fbuz', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ez_i_emp_podano_v_rpn', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r2_poluchen_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r2_poluchen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ap_r2_podpisan_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('gr_r2_prostavlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('r2_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('smr_odn_fakt_aop_soglsovano_io_cs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_cs_zakazano', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_zakazano_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_polucheno_v_polnom_obeme_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_gotova_k_smr_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_gotova_k_smr_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_zakazano_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_bs_mts_vypisano', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('planovaya_data_polucheniya_oborudovaniya_bs', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_polucheno_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('dozakazy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nomer_zayavki_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_komentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_ts_zakaz_obor_ya', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('sites', sa.Column('zayavka_na_oborudovanie_ts_otpravlena_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_ts_mts_vypisano', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('planovaya_data_polucheniya_oborudovaniya_ts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_ts_polucheno', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('nomer_zayavki_ts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('oborudovanie_polucheno_v_polnom_obeme', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_oborudovanie', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('dostup_na_bs_smr_status', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_dostup_na_bs_smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('neobkhodimost_soprovozhdeniya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('klyuchi', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zapros_int_nykh_dannykh_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('int_nye_dannye_polucheny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fio_otvetstvennogo_za_sim', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('sim_karta_um_40', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('um_40_v_rabote_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pasport_na_el_schetchik_poluchen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pasport_na_el_schetchik_peredan_v_oge', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smr_klassifikator', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('smr_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('polnyy_komplekt_oborudovaniya', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('prognoz_dopuska_na_bs', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('data_pnr_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('nedelya_pnr_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nedelya_smr_prognoz', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nedelya_pnr_prognoz', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('region_brigady', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fio_brigadir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('telefon', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('nachalo_smr_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('nachalo_smr_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zavershenie_smr_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zavershenie_smr_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pnr_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('pnr_fakt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('nedelya_pnr_fakt', sa.Numeric(precision=18, scale=4), nullable=True))
    op.add_column('sites', sa.Column('pnr_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('avarii_po_bs', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('km_kommentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('avtovyshka_kol_vo', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('raschet_premialnoy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fo_predostavlen_nsn_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_status_nsn', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fo_status_nsn_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_prinyat_nsn_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_nsn', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fo_otpravlen_io_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_otpravlen_io_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_io_status', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('fo_io_status_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_prinyat_io_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fo_prinyat_io_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentrii_fo_io', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('id_podgotovlena_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_peredana_v_mts_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_peredana_v_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_proverena_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('id_proverena_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_prinyata_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('id_prinyata_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('id_priemka_kommentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('bs_vystavlena_na_priemku_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('bs_vystavlena_na_priemku_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('priemka_bs_plan_nsn_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('priemka_bs_plan_nsn_vermya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('priemka_bs_plan_mts_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('priemka_bs_plan_mts_vremya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('priemka_provedena_fakt_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('priemka_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vn_poluchena_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('vn_poluchena_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('vd_poluchena_data', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('polucheny_zamechaniya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_pir_status', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_pir_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_pir_ustraneny_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('vo_otvezena_v_mts_v_bumage_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('vo_prinyata_v_mts_v_bumage_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_pir_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_smr_kommentarii', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('trebuemye_raskh_materialy_dlya_ustraneniya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('trebuemoe_oborudovanie_dlya_ustraneniya_mts', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('ustranenie_zamechaniy_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('vn_peredana_brigade', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('fio_brigadira', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zmechaniya_smr_status', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_smr_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ustranenie_vn_otpravleno_v_mts_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ustranenie_vn_otpravleno_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ustranenie_vn_provereno_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_po_otdelam_mts_status', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('zamechaniya_po_otdelam_mts_kommentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('smr_prinyat_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('bs_prinyata_mts_polnostyu_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('bs_prinyata_mts_polnostyu', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('atp_podgotovlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('atp_podpisan_nsn', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('atp_peredan_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('atp_podpisan_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podgotovlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan_plan', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ks_11_podgotovlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ks_11_podpisan_nsn', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ks_11_peredana_v_mts', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ks_11_podpisana_polnostyu_plan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ks_11_podpisana_polnostyu_data', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('dokumenty_na_oplatu_podany', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('gr_smr_prostavlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('gr_smr_komentariy', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_k_zakazu_pir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_zakaz_na_pir', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_pir_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_pir_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_pir_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_pir_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_pir_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('srok_okonchaniya_rabot_po_pir', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_pir_v_storonu_po_vypuschen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('obosnovanie_prodleniya_zakaza_pir', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('pir_faktura_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('novyy_srok_okonchaniya_zakaza_pir_dlya_prodleniya', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otsrochka_pir_soglasovana', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_k_zakazu_smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_zakaz_na_smr', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_smr_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_smr_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_smr_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_smr_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_smr_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('srok_okonchaniya_rabot_po_smr', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_smr_v_storonu_po_vypuschen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('obosnovanie_prodleniya_zakaza_smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('smr_faktura_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('novyy_srok_okonchaniya_zakaza_smr_dlya_prodleniya', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otsrochka_smr_soglasovana', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_k_ds_smr', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_ds_k_smr', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_smr_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_ds_na_smr_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_ds_na_smr_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_smr_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('ds_na_smr_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_k_zakazu_r1', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_zakaz_na_r1', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r1_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_r1_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_r1_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r1_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r1_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('srok_okonchaniya_rabot_po_r1', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r1_v_storonu_po_vypuschen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('obosnovanie_prodleniya_zakaza_r1', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('r1_faktura_tekst', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('novyy_srok_okonchaniya_zakaza_r1_dlya_prodleniya', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('otsrochka_r1_soglasovana', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentariy_k_zakazu_r2', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_zakaz_na_r2', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r2_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_r2_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_r2_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r2_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r2_podpisan', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('srok_okonchaniya_rabot_po_r2', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_r2_v_storonu_po_vypuschen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('obosnovanie_prodleniya_zakaza_r2', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('novyy_srok_okonchaniya_zakaza_r2_dlya_prodleniya', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('servisnyy_nomer', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('kommentarii_k_zakazu_na_avtovyshku', sa.Text(), nullable=True))
    op.add_column('sites', sa.Column('vypustit_zakaz_na_avtovyshku', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_avtovyshku_v_rabote', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_avtovyshku_otpravlena', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('smeta_na_avtovyshku_soglasovana', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_avtovyshku_otpravlen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('zakaz_na_avtovyshku_podpisan', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('sites', 'zakaz_na_avtovyshku_podpisan')
    op.drop_column('sites', 'zakaz_na_avtovyshku_otpravlen')
    op.drop_column('sites', 'smeta_na_avtovyshku_soglasovana')
    op.drop_column('sites', 'smeta_na_avtovyshku_otpravlena')
    op.drop_column('sites', 'zakaz_na_avtovyshku_v_rabote')
    op.drop_column('sites', 'vypustit_zakaz_na_avtovyshku')
    op.drop_column('sites', 'kommentarii_k_zakazu_na_avtovyshku')
    op.drop_column('sites', 'servisnyy_nomer')
    op.drop_column('sites', 'novyy_srok_okonchaniya_zakaza_r2_dlya_prodleniya')
    op.drop_column('sites', 'obosnovanie_prodleniya_zakaza_r2')
    op.drop_column('sites', 'zakaz_na_r2_v_storonu_po_vypuschen')
    op.drop_column('sites', 'srok_okonchaniya_rabot_po_r2')
    op.drop_column('sites', 'zakaz_na_r2_podpisan')
    op.drop_column('sites', 'zakaz_na_r2_otpravlen')
    op.drop_column('sites', 'smeta_na_r2_soglasovana')
    op.drop_column('sites', 'smeta_na_r2_otpravlena')
    op.drop_column('sites', 'zakaz_na_r2_v_rabote')
    op.drop_column('sites', 'vypustit_zakaz_na_r2')
    op.drop_column('sites', 'kommentariy_k_zakazu_r2')
    op.drop_column('sites', 'otsrochka_r1_soglasovana')
    op.drop_column('sites', 'novyy_srok_okonchaniya_zakaza_r1_dlya_prodleniya')
    op.drop_column('sites', 'r1_faktura_tekst')
    op.drop_column('sites', 'obosnovanie_prodleniya_zakaza_r1')
    op.drop_column('sites', 'zakaz_na_r1_v_storonu_po_vypuschen')
    op.drop_column('sites', 'srok_okonchaniya_rabot_po_r1')
    op.drop_column('sites', 'zakaz_na_r1_podpisan')
    op.drop_column('sites', 'zakaz_na_r1_otpravlen')
    op.drop_column('sites', 'smeta_na_r1_soglasovana')
    op.drop_column('sites', 'smeta_na_r1_otpravlena')
    op.drop_column('sites', 'zakaz_na_r1_v_rabote')
    op.drop_column('sites', 'vypustit_zakaz_na_r1')
    op.drop_column('sites', 'kommentariy_k_zakazu_r1')
    op.drop_column('sites', 'ds_na_smr_podpisan')
    op.drop_column('sites', 'ds_na_smr_otpravlen')
    op.drop_column('sites', 'smeta_ds_na_smr_soglasovana')
    op.drop_column('sites', 'smeta_ds_na_smr_otpravlena')
    op.drop_column('sites', 'ds_na_smr_v_rabote')
    op.drop_column('sites', 'vypustit_ds_k_smr')
    op.drop_column('sites', 'kommentariy_k_ds_smr')
    op.drop_column('sites', 'otsrochka_smr_soglasovana')
    op.drop_column('sites', 'novyy_srok_okonchaniya_zakaza_smr_dlya_prodleniya')
    op.drop_column('sites', 'smr_faktura_tekst')
    op.drop_column('sites', 'obosnovanie_prodleniya_zakaza_smr')
    op.drop_column('sites', 'zakaz_na_smr_v_storonu_po_vypuschen')
    op.drop_column('sites', 'srok_okonchaniya_rabot_po_smr')
    op.drop_column('sites', 'zakaz_na_smr_podpisan')
    op.drop_column('sites', 'zakaz_na_smr_otpravlen')
    op.drop_column('sites', 'smeta_na_smr_soglasovana')
    op.drop_column('sites', 'smeta_na_smr_otpravlena')
    op.drop_column('sites', 'zakaz_na_smr_v_rabote')
    op.drop_column('sites', 'vypustit_zakaz_na_smr')
    op.drop_column('sites', 'kommentariy_k_zakazu_smr')
    op.drop_column('sites', 'otsrochka_pir_soglasovana')
    op.drop_column('sites', 'novyy_srok_okonchaniya_zakaza_pir_dlya_prodleniya')
    op.drop_column('sites', 'pir_faktura_tekst')
    op.drop_column('sites', 'obosnovanie_prodleniya_zakaza_pir')
    op.drop_column('sites', 'zakaz_na_pir_v_storonu_po_vypuschen')
    op.drop_column('sites', 'srok_okonchaniya_rabot_po_pir')
    op.drop_column('sites', 'zakaz_na_pir_podpisan')
    op.drop_column('sites', 'zakaz_na_pir_otpravlen')
    op.drop_column('sites', 'smeta_na_pir_soglasovana')
    op.drop_column('sites', 'smeta_na_pir_otpravlena')
    op.drop_column('sites', 'zakaz_na_pir_v_rabote')
    op.drop_column('sites', 'vypustit_zakaz_na_pir')
    op.drop_column('sites', 'kommentariy_k_zakazu_pir')
    op.drop_column('sites', 'gr_smr_komentariy')
    op.drop_column('sites', 'gr_smr_prostavlen')
    op.drop_column('sites', 'dokumenty_na_oplatu_podany')
    op.drop_column('sites', 'ks_11_podpisana_polnostyu_data')
    op.drop_column('sites', 'ks_11_podpisana_polnostyu_plan')
    op.drop_column('sites', 'ks_11_peredana_v_mts')
    op.drop_column('sites', 'ks_11_podpisan_nsn')
    op.drop_column('sites', 'ks_11_podgotovlen')
    op.drop_column('sites', 'akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan')
    op.drop_column('sites', 'akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podpisan_plan')
    op.drop_column('sites', 'akt_chastichnogo_zakrytiya_bez_uslug_dlya_oge_podgotovlen')
    op.drop_column('sites', 'atp_podpisan_data')
    op.drop_column('sites', 'atp_peredan_v_mts')
    op.drop_column('sites', 'atp_podpisan_nsn')
    op.drop_column('sites', 'atp_podgotovlen')
    op.drop_column('sites', 'bs_prinyata_mts_polnostyu')
    op.drop_column('sites', 'bs_prinyata_mts_polnostyu_plan')
    op.drop_column('sites', 'smr_prinyat_mts')
    op.drop_column('sites', 'zamechaniya_po_otdelam_mts_kommentariy')
    op.drop_column('sites', 'zamechaniya_po_otdelam_mts_status')
    op.drop_column('sites', 'ustranenie_vn_provereno_mts')
    op.drop_column('sites', 'ustranenie_vn_otpravleno_v_mts')
    op.drop_column('sites', 'ustranenie_vn_otpravleno_v_mts_plan')
    op.drop_column('sites', 'zamechaniya_smr_data')
    op.drop_column('sites', 'zmechaniya_smr_status')
    op.drop_column('sites', 'fio_brigadira')
    op.drop_column('sites', 'vn_peredana_brigade')
    op.drop_column('sites', 'ustranenie_zamechaniy_plan')
    op.drop_column('sites', 'trebuemoe_oborudovanie_dlya_ustraneniya_mts')
    op.drop_column('sites', 'trebuemye_raskh_materialy_dlya_ustraneniya')
    op.drop_column('sites', 'zamechaniya_smr_kommentarii')
    op.drop_column('sites', 'zamechaniya_pir_kommentarii')
    op.drop_column('sites', 'vo_prinyata_v_mts_v_bumage_data')
    op.drop_column('sites', 'vo_otvezena_v_mts_v_bumage_data')
    op.drop_column('sites', 'zamechaniya_pir_ustraneny_data')
    op.drop_column('sites', 'zamechaniya_pir_data')
    op.drop_column('sites', 'zamechaniya_pir_status')
    op.drop_column('sites', 'polucheny_zamechaniya')
    op.drop_column('sites', 'vd_poluchena_data')
    op.drop_column('sites', 'vn_poluchena_data')
    op.drop_column('sites', 'vn_poluchena_plan')
    op.drop_column('sites', 'priemka_kommentarii')
    op.drop_column('sites', 'priemka_provedena_fakt_data')
    op.drop_column('sites', 'priemka_bs_plan_mts_vremya')
    op.drop_column('sites', 'priemka_bs_plan_mts_data')
    op.drop_column('sites', 'priemka_bs_plan_nsn_vermya')
    op.drop_column('sites', 'priemka_bs_plan_nsn_data')
    op.drop_column('sites', 'bs_vystavlena_na_priemku_data')
    op.drop_column('sites', 'bs_vystavlena_na_priemku_plan')
    op.drop_column('sites', 'id_priemka_kommentariy')
    op.drop_column('sites', 'id_prinyata_data')
    op.drop_column('sites', 'id_prinyata_plan')
    op.drop_column('sites', 'id_proverena_data')
    op.drop_column('sites', 'id_proverena_plan')
    op.drop_column('sites', 'id_peredana_v_mts_data')
    op.drop_column('sites', 'id_peredana_v_mts_plan')
    op.drop_column('sites', 'id_podgotovlena_data')
    op.drop_column('sites', 'kommentrii_fo_io')
    op.drop_column('sites', 'fo_prinyat_io_data')
    op.drop_column('sites', 'fo_prinyat_io_plan')
    op.drop_column('sites', 'fo_io_status_data')
    op.drop_column('sites', 'fo_io_status')
    op.drop_column('sites', 'fo_otpravlen_io_data')
    op.drop_column('sites', 'fo_otpravlen_io_plan')
    op.drop_column('sites', 'kommentariy_nsn')
    op.drop_column('sites', 'fo_prinyat_nsn_data')
    op.drop_column('sites', 'fo_status_nsn_data')
    op.drop_column('sites', 'fo_status_nsn')
    op.drop_column('sites', 'fo_predostavlen_nsn_data')
    op.drop_column('sites', 'raschet_premialnoy')
    op.drop_column('sites', 'avtovyshka_kol_vo')
    op.drop_column('sites', 'km_kommentariy')
    op.drop_column('sites', 'avarii_po_bs')
    op.drop_column('sites', 'pnr_kommentarii')
    op.drop_column('sites', 'nedelya_pnr_fakt')
    op.drop_column('sites', 'pnr_fakt')
    op.drop_column('sites', 'pnr_plan')
    op.drop_column('sites', 'zavershenie_smr_fakt')
    op.drop_column('sites', 'zavershenie_smr_plan')
    op.drop_column('sites', 'nachalo_smr_fakt')
    op.drop_column('sites', 'nachalo_smr_plan')
    op.drop_column('sites', 'telefon')
    op.drop_column('sites', 'fio_brigadir')
    op.drop_column('sites', 'region_brigady')
    op.drop_column('sites', 'nedelya_pnr_prognoz')
    op.drop_column('sites', 'nedelya_smr_prognoz')
    op.drop_column('sites', 'nedelya_pnr_plan')
    op.drop_column('sites', 'data_pnr_plan')
    op.drop_column('sites', 'prognoz_dopuska_na_bs')
    op.drop_column('sites', 'polnyy_komplekt_oborudovaniya')
    op.drop_column('sites', 'smr_kommentarii')
    op.drop_column('sites', 'smr_klassifikator')
    op.drop_column('sites', 'pasport_na_el_schetchik_peredan_v_oge')
    op.drop_column('sites', 'pasport_na_el_schetchik_poluchen')
    op.drop_column('sites', 'um_40_v_rabote_data')
    op.drop_column('sites', 'sim_karta_um_40')
    op.drop_column('sites', 'fio_otvetstvennogo_za_sim')
    op.drop_column('sites', 'int_nye_dannye_polucheny_data')
    op.drop_column('sites', 'zapros_int_nykh_dannykh_data')
    op.drop_column('sites', 'klyuchi')
    op.drop_column('sites', 'neobkhodimost_soprovozhdeniya')
    op.drop_column('sites', 'kommentarii_dostup_na_bs_smr')
    op.drop_column('sites', 'dostup_na_bs_smr_status')
    op.drop_column('sites', 'kommentariy_oborudovanie')
    op.drop_column('sites', 'oborudovanie_polucheno_v_polnom_obeme')
    op.drop_column('sites', 'nomer_zayavki_ts')
    op.drop_column('sites', 'oborudovanie_ts_polucheno')
    op.drop_column('sites', 'planovaya_data_polucheniya_oborudovaniya_ts')
    op.drop_column('sites', 'oborudovanie_ts_mts_vypisano')
    op.drop_column('sites', 'zayavka_na_oborudovanie_ts_otpravlena_v_mts')
    op.drop_column('sites', 'bs_ts_zakaz_obor_ya')
    op.drop_column('sites', 'oborudovanie_komentarii')
    op.drop_column('sites', 'nomer_zayavki_bs')
    op.drop_column('sites', 'dozakazy')
    op.drop_column('sites', 'oborudovanie_polucheno_data')
    op.drop_column('sites', 'planovaya_data_polucheniya_oborudovaniya_bs')
    op.drop_column('sites', 'oborudovanie_bs_mts_vypisano')
    op.drop_column('sites', 'oborudovanie_zakazano_data')
    op.drop_column('sites', 'bs_gotova_k_smr_kommentarii')
    op.drop_column('sites', 'bs_gotova_k_smr_data')
    op.drop_column('sites', 'oborudovanie_polucheno_v_polnom_obeme_plan')
    op.drop_column('sites', 'oborudovanie_zakazano_plan')
    op.drop_column('sites', 'oborudovanie_cs_zakazano')
    op.drop_column('sites', 'smr_odn_fakt_aop_soglsovano_io_cs')
    op.drop_column('sites', 'r2_kommentarii')
    op.drop_column('sites', 'gr_r2_prostavlen')
    op.drop_column('sites', 'ap_r2_podpisan_mts')
    op.drop_column('sites', 'r2_poluchen')
    op.drop_column('sites', 'r2_poluchen_plan')
    op.drop_column('sites', 'ez_i_emp_podano_v_rpn')
    op.drop_column('sites', 'ez_i_emp_polucheny_ot_fbuz')
    op.drop_column('sites', 'pi_podan_na_ez2_v_fbuz')
    op.drop_column('sites', 'protokol_izmereniy_poluchen_data')
    op.drop_column('sites', 'r1_otpravlen_vo_fbuz_data')
    op.drop_column('sites', 'r2_status_data')
    op.drop_column('sites', 'r2_status_tekst')
    op.drop_column('sites', 'r1_kommentarii')
    op.drop_column('sites', 'gr_r1_prostavlen')
    op.drop_column('sites', 'ap_r1_podpisan_mts')
    op.drop_column('sites', 'r1_poluchen_data')
    op.drop_column('sites', 'r1_poluchen_plan')
    op.drop_column('sites', 'ez1_podano_na_r1_data')
    op.drop_column('sites', 'ez1_podano_na_r1_plan')
    op.drop_column('sites', 'ez_kommentarii')
    op.drop_column('sites', 'ez1_polucheno_ot_fbuz_data')
    op.drop_column('sites', 'psez_otpravlen_v_fbuz_data')
    op.drop_column('sites', 'psez_otpravlen_v_fbuz_plan')
    op.drop_column('sites', 'r1_status_data')
    op.drop_column('sites', 'r1_status_tekst')
    op.drop_column('sites', 'psez_kommentarii')
    op.drop_column('sites', 'psez_podpisan_mts_data')
    op.drop_column('sites', 'psez_otdan_na_podpisanie_v_mts_data')
    op.drop_column('sites', 'psez_vypuschen_data')
    op.drop_column('sites', 'psez_vydan_v_rabotu_data')
    op.drop_column('sites', 'psez_vypuschen_plan')
    op.drop_column('sites', 'otvet_prto')
    op.drop_column('sites', 'zapros_prto')
    op.drop_column('sites', 'nalichie_so')
    op.drop_column('sites', 'kommentarii_ds_izm_tz')
    op.drop_column('sites', 'ds_na_izmenenie_tz_podpisan_data')
    op.drop_column('sites', 'ds_na_izmenenie_tz_otpravlen_mts_data')
    op.drop_column('sites', 'ds_na_izmenenie_adresa_podpisan_data')
    op.drop_column('sites', 'ds_na_izmenenie_adresa_otpravlen_mts_data')
    op.drop_column('sites', 'dogovor_arendy_poluchen_ot_mts_data')
    op.drop_column('sites', 'adres_dogovora_arendy_rnr')
    op.drop_column('sites', 'po_r2')
    op.drop_column('sites', 'po_r1')
    op.drop_column('sites', 'pd_el_snab_soglasovan_s_setevoy_organizatsiey')
    op.drop_column('sites', 'pd_el_snab_soglasovan_s_ad')
    op.drop_column('sites', 'dogovor_elektrosnabzheniya_bs_podgotovlen')
    op.drop_column('sites', 'tu_na_elektrosnabzhenie_poluchen_data')
    op.drop_column('sites', 'zapros_tu_elektrosnayuzheniya_otpravlen_data')
    op.drop_column('sites', 'oformlenie_dogovora_tekhnologicheskogo_prisoedineniya_k_es')
    op.drop_column('sites', 'tip_ves')
    op.drop_column('sites', 'ekspertiza_komentariy')
    op.drop_column('sites', 'km_na_ams')
    op.drop_column('sites', 'f1a_vydana_v_rabotu_data')
    op.drop_column('sites', 'f1a_zaproshena_v_mts_data')
    op.drop_column('sites', 'ekspertiza_gotova_data')
    op.drop_column('sites', 'plan_predostavleniya_ekspertizy_data')
    op.drop_column('sites', 'ekspertiza_vydana_v_rabotu_data')
    op.drop_column('sites', 'ispolnitel_ekspertizy')
    op.drop_column('sites', 'pozitsiya_s_zakazchikom')
    op.drop_column('sites', 'neobkhodimost_rns_epb')
    op.drop_column('sites', 'kommentarii_4_etap')
    op.drop_column('sites', 'prioritety_sdachi_usl_smr')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_i_arbp_otchet_psi_prinyat_mts_plan')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_i_arbp_otchet_psi_peredan_v_mts')
    op.drop_column('sites', 'otchet_psi_podgotovlen_data')
    op.drop_column('sites', 'otchet_psi_podgotovlen_plan')
    op.drop_column('sites', 'otchet_psi_v_rabote')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_arbp_otchet_prinyaty_io_plan')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_arbp_otchet_peredany_io')
    op.drop_column('sites', 'arbp_podpisan_v_mts')
    op.drop_column('sites', 'arbp_otpravlen_na_podpisanie_v_mts')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_arbp_podgotovlena')
    op.drop_column('sites', 'spravka_o_vypolnenii_tu_arbp_v_rabote')
    op.drop_column('sites', 'sa_pir_prostavlen')
    op.drop_column('sites', 'kommentarii_em')
    op.drop_column('sites', 'prioritety_sdachi_usl_pir')
    op.drop_column('sites', 'albom_em_prinyat_oge_usl_20_22')
    op.drop_column('sites', 'albom_em_prinyat_oge_usl_20_22_plan')
    op.drop_column('sites', 'albom_em_sdan_v_oge_usl_20_22')
    op.drop_column('sites', 'albom_em_podpisan_mgen_i_io')
    op.drop_column('sites', 'albom_em_podpisan_mgen')
    op.drop_column('sites', 'albom_em_sdan_v_mgen')
    op.drop_column('sites', 'organizatsiya_soglasuyuschaya_albom_em')
    op.drop_column('sites', 'nomer_tp')
    op.drop_column('sites', 'kommentarii_pir')
    op.drop_column('sites', 'plan_sdachi_pir')
    op.drop_column('sites', 'pir_status_data')
    op.drop_column('sites', 'pir_status_tekst')
    op.drop_column('sites', 'pir_prinyat_mts_bez_usl_20_22')
    op.drop_column('sites', 'pir_prinyat_mts_bez_usl_20_22_plan')
    op.drop_column('sites', 'pir_proveren_mts_zamechaniya')
    op.drop_column('sites', 'pir_na_proverke_v_mts')
    op.drop_column('sites', 'pir_na_proverke_v_mts_plan')
    op.drop_column('sites', 'pir_vypuschen')
    op.drop_column('sites', 'pir_otdan_v_rabotu')
    op.drop_column('sites', 'pir_otdan_v_rabotu_komu')
    op.drop_column('sites', 'km')
    op.drop_column('sites', 'status_tz')
    op.drop_column('sites', 'tz_vypuscheno_data')
    op.drop_column('sites', 'aop_kommentarii')
    op.drop_column('sites', 'aop_podpisan_io_ad_data')
    op.drop_column('sites', 'aop_soglasovan_io_ad_data')
    op.drop_column('sites', 'zamechaniya_po_aop_ot_io_ad_polucheny_data')
    op.drop_column('sites', 'aop_otpravlen_io_ad_na_soglasovanie_data')
    op.drop_column('sites', 'aop_soglasovan_io_ad_plan')
    op.drop_column('sites', 'aop_soglasovan_mts_v_ev_fakt')
    op.drop_column('sites', 'aop_soglasovan_mts_v_ev_plan')
    op.drop_column('sites', 'aop_status_data')
    op.drop_column('sites', 'aop_status_tekst')
    op.drop_column('sites', 'aop_vypuschen_data')
    op.drop_column('sites', 'aop_otdan_v_rabotu_komu')
    op.drop_column('sites', 'aop_vypuschen_plan')
    op.drop_column('sites', 'kommentarii_tu')
    op.drop_column('sites', 'tu_podpisany_data')
    op.drop_column('sites', 'tu_io_polucheny_data')
    op.drop_column('sites', 'tu_io_zaprosheny_data')
    op.drop_column('sites', 'kommentarii_bs_ts')
    op.drop_column('sites', 'tu_ad_ts_polucheny_data')
    op.drop_column('sites', 'tu_ad_ts_zaprosheny_data')
    op.drop_column('sites', 'neobkhodimost_polucheniya_tu')
    op.drop_column('sites', 'obsledovanie_bs_ts_fakt')
    op.drop_column('sites', 'kontakt_po_dostupu_na_ts')
    op.drop_column('sites', 'status_dostupa_na_otvetku')
    op.drop_column('sites', 'vladelets_ao_ts')
    op.drop_column('sites', 'tip_ao_ts')
    op.drop_column('sites', 'adres_ts')
    op.drop_column('sites', 'bs_ts')
    op.drop_column('sites', 'tip_ts')
    op.drop_column('sites', 'kandidat_ts_predostavlen')
    op.drop_column('sites', 'kommentarii_obsledovanie')
    op.drop_column('sites', 'fo_peredan_v_mts_fakt')
    op.drop_column('sites', 'obsledovanie_bs_fakt')
    op.drop_column('sites', 'obsledovanie_bs_plan')
    op.drop_column('sites', 'obsledovanie_bs_ispolnitel')
    op.drop_column('sites', 'kontakt_po_dostupu_na_bs')
    op.drop_column('sites', 'kommentari_dostup')
    op.drop_column('sites', 'dostup_dlya_obsledovaniya')
    op.drop_column('sites', 'karta_ts_poluchena')
    op.drop_column('sites', 'id_polucheny_data')
    op.drop_column('sites', 'prognoz_dopuska_na_smr')
    op.drop_column('sites', 'kommentarii_odn')
    op.drop_column('sites', 'fakt_smr_odn')
    op.drop_column('sites', 'plan_smr_odn_nedelya')
    op.drop_column('sites', 'plan_smr_odn')
    op.drop_column('sites', 'bs_otozvana')
    op.drop_column('sites', 'bs_vydana_v_rabotu_kommentariy')
    op.drop_column('sites', 'bs_vydana_v_rabotu')
    op.drop_column('sites', 'primechanie')
    op.drop_column('sites', 'otvetsvennyy_oirp')
    op.drop_column('sites', 'otvetsvennyy_oa')
    op.drop_column('sites', 'vysota_podvesa')
    op.drop_column('sites', 'bs_io')
    op.drop_column('sites', 'vladelets_bs')
    op.drop_column('sites', 'tip_bs')
    op.drop_column('sites', 'r2')
    op.drop_column('sites', 'r1')
    op.drop_column('sites', 'pir')
    op.drop_column('sites', 'smr')
    op.drop_column('sites', 'status_bs')
    op.drop_column('sites', 'povtor_bs')
    op.drop_column('sites', 'koordinaty')
    op.drop_column('sites', 'diapazony')
    op.drop_column('sites', 'diapazon_dlya_stsepki')
    op.drop_column('sites', 'stsepka')
    op.drop_column('sites', 'tip_rabot')
    op.drop_column('sites', 'bs')
